INSERT INTO users (name, mail, gender, "like") VALUES ('Alice', 'alice@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Bob', 'bob@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Charlie', 'charlie@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Diana', 'diana@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Edward', 'edward@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Fiona', 'fiona@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('George', 'george@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Hannah', 'hannah@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Ian', 'ian@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Julia', 'julia@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Kyle', 'kyle@example.com', 'M', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Linda', 'linda@example.com', 'F', false, null);
INSERT INTO users (name, mail, gender, "like") VALUES ('Kaito', null, 'M', false, null);
-- UPDATE users SET  = false;
