"""empty message

Revision ID: bf7fe1c4d123
Revises: a9a78904c117
Create Date: 2024-02-01 07:29:40.747440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7fe1c4d123'
down_revision = 'a9a78904c117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_pair')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_pair', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
